
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  # username: root
  # password:

development:
  <<: *default
  database: FacebookHelper_development

test:
  <<: *default
  database: FacebookHelper_test

production:
  <<: *default
  database: FacebookHelper_production
  username: FacebookHelper
  password: <%= ENV['FACEBOOKHELPER_DATABASE_PASSWORD'] %>
